### ISSUE TITLE
Support live steam

### ISSUE THREAD

**Issue by hiroppy** [ericblade/quagga2-reader-qr#81]
Hi, I would like to ask can this qrcode reader work with live stream? Because I confirmed my repo using this reader but when I use `inputstream.type = 'livestream'`, quagga2 can't read qrcode.(other readers such as `ean_reader` can be read). Thanks.

**Comment by ericblade** [comment]
I haven't personally tested it (i guess i'd have to install it into my website and give it a shot to find out... i could probably do that sometime..), but other users have reported that it did in fact work, with the most recent versions of both this and @ericblade/quagga2.

**Comment by hiroppy** [comment]
Thank you so much!

**Comment by ericblade** [comment]
no worries, just wanted to make sure we had the right repo :-)  it's just.. this has been on the backburner for entirely too long, i feel really bad that i haven't got to checking this myself, but other people attested that it does work..  

i just don't know when i'll get the time to try and set it up myself

**Comment by hiroppy** [comment]
ok, thanks. anyway, thank you for the development of quagga2!

**Comment by 188599** [comment]
I also not having much luck trying to use it.

Relevant code:

```ts
import Quagga, { QuaggaJSResultObject } from '@ericblade/quagga2';
import QrCodeReader from '@ericblade/quagga2-reader-qr';

Quagga.init(
    {
        inputStream: {
            target: document.querySelector('#interactive.viewport'),
            constraints: { facingMode: 'environment' },
            area: {
                top: '40%',
                right: '0%',
                left: '0%',
                bottom: '40%'
            },
        },
        decoder: { readers: ['qrcode'] }
    },
    err => {
        ...
    });
```

And my package.json:

```json
{
  "dependencies": {
      "@ericblade/quagga2": "^1.2.6",
      "@ericblade/quagga2-reader-qr": "git+https://github.com/ericblade/quagga2-reader-qr.git"
  }
}
```

**Comment by ericblade** [comment]
@188599 is it working?  

Care to post the working bit here or a CodePen ?  Thanks!!

**Comment by 188599** [comment]
> @188599 is it working?
> 
> Care to post the working bit here or a CodePen ? Thanks!!

Sorry, I had turned it into a rxjs `Observable` but forgot to subscribe to it (which happens an embarrassing amount of times), so the code wasn't running. Like I said, silly mistake.

After I fixed that, it worked perfectly.

**Comment by ericblade** [comment]
@188599 so livestream is working with QR? Awesome!  I think I need to do the work to get this published to npm then and hopefully everything will be great from there :-D

@hiroppy

**Comment by 188599** [comment]
Yes. Publishing to npm would be really nice, if possible.

**Comment by hiroppy** [comment]
oh, really? so... maybe I mistook something. thank you for the ping, I'll try again

**Comment by ericblade** [comment]
also https://github.com/ericblade/quagga2/issues/240#issuecomment-712491908
