### ISSUE TITLE
QR Reader not working mobile Safari on iOS (13.7)

### ISSUE THREAD

**Issue by Hakio18** [ericblade/quagga2-reader-qr#89]
Hi, thank you for this library.

I'm sorry to annoy you but the reader doesn't seems to work on mobile safari on iOS (but it works on the Mac Version of safari). Don't know if it comes from the QR scanner's library, jsQR, or from something else. I tried to replace it with a homemade CodeReader based on ZXing's QR Code reader, but unsuccessfully.
Moreover, like you, I don't have an iOS support to check the error returned, if someone can check and share it.
My code can be tested here if you want to try : https://testflasher.netlify.app/
In safari mobile on iOS, it doesn't display the camera, must have an error on QR code reading or init

**Comment by ericblade** [comment]
Hi, closing pending further input
